# Generated by Django 5.0.1 on 2024-04-09 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, verbose_name='Códgio')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Departamento')),
            ],
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': []},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Perfil'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=4, verbose_name='Códgio')),
                ('descripcion', models.CharField(max_length=60, verbose_name='Municipio')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.departamento')),
            ],
        ),
    ]
