# Generated by Django 4.2.6 on 2024-03-05 22:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=12, verbose_name='Código')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('V', 'Vigente'), ('B', 'Bloqueada'), ('E', 'Eliminada')], max_length=1, verbose_name='Estado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Ult. Actualizacion')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='puesto_superior', to='usuarios.puesto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2024, 3, 5), verbose_name='Fecha de ingreso'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fin')),
                ('estado', models.CharField(choices=[('P', 'Propuesto'), ('A', 'Autorizado'), ('C', 'Confirmado'), ('N', 'Anulado')], default='P', max_length=1, verbose_name='Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PuestoSuplente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vigente', models.BooleanField(default=True, verbose_name='Estado')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.puesto')),
                ('suplente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puesto_suplente', to='usuarios.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalVacaciones',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('fecha_inicio', models.DateField(verbose_name='Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fin')),
                ('estado', models.CharField(choices=[('P', 'Propuesto'), ('A', 'Autorizado'), ('C', 'Confirmado'), ('N', 'Anulado')], default='P', max_length=1, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vacaciones',
                'verbose_name_plural': 'historical vacacioness',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPuestoSuplente',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('vigente', models.BooleanField(default=True, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('puesto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.puesto')),
                ('suplente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.puesto')),
            ],
            options={
                'verbose_name': 'historical puesto suplente',
                'verbose_name_plural': 'historical puesto suplentes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPuesto',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('codigo', models.CharField(max_length=12, verbose_name='Código')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('V', 'Vigente'), ('B', 'Bloqueada'), ('E', 'Eliminada')], max_length=1, verbose_name='Estado')),
                ('actualizado', models.DateTimeField(blank=True, editable=False, verbose_name='Ult. Actualizacion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('padre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.puesto')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical puesto',
                'verbose_name_plural': 'historical puestos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
