# Generated by Django 4.2.6 on 2024-03-05 22:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2024, 3, 5), verbose_name='Fecha de ingreso'),
            preserve_default=False,
        ),
    ]
