# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import unidecode
from usuarios.models import Departamento, Municipio

Departamentos = [
    ('01','Guatemala'),
    ('02','El Progreso'),
    ('03','Sacatepéquez'),
    ('04','Chimaltenango'),
    ('05','Escuintla'),
    ('06','Santa Rosa'),
    ('07','Sololá'),
    ('08','Totonicapán'),
    ('09','Quetzaltenango'),
    ('10','Suchitepéquez'),
    ('11','Retalhuleu'),
    ('12','San Marcos'),
    ('13','Huehuetenango'),
    ('14','Quiché'),
    ('15','Baja Verapaz'),
    ('16','Alta Verapaz'),
    ('17','Petén'),
    ('18','Izabal'),
    ('19','Zacapa'),
    ('20','Chiquimula'),
    ('21','Jalapa'),
    ('22','Jutiapa'),
]

Municipios = [
    ('Guatemala','0101','Guatemala'),
    ('Guatemala','0102','Santa Catarina Pinula'),
    ('Guatemala','0103','San José Pinula'),
    ('Guatemala','0104','San José del Golfo'),
    ('Guatemala','0105','Palencia'),
    ('Guatemala','0106','Chinautla'),
    ('Guatemala','0107','San Pedro Ayampuc'),
    ('Guatemala','0108','Mixco'),
    ('Guatemala','0109','San Pedro Sacatepéquez'),
    ('Guatemala','0110','San Juan Sacatepéquez'),
    ('Guatemala','0111','San Raymundo'),
    ('Guatemala','0112','Chuarrancho'),
    ('Guatemala','0113','Fraijanes'),
    ('Guatemala','0114','Amatitlán'),
    ('Guatemala','0115','Villa Nueva'),
    ('Guatemala','0116','Villa Canales'),
    ('Guatemala','0117','Petapa'),
    ('El Progreso','0201','Guastatoya'),
    ('El Progreso','0202','Morazán'),
    ('El Progreso','0203','San Agustín Acasaguastlán'),
    ('El Progreso','0204','San Cristóbal Acasaguastlán'),
    ('El Progreso','0205','El Jícaro'),
    ('El Progreso','0206','Sansare'),
    ('El Progreso','0207','Sanarate'),
    ('El Progreso','0208','San Antonio la Paz'),
    ('Sacatepéquez','0301','Antigua Guatemala'),
    ('Sacatepéquez','0302','Jocotenango'),
    ('Sacatepéquez','0303','Pastores'),
    ('Sacatepéquez','0304','Sumpango'),
    ('Sacatepéquez','0305','Santo Domingo Xenacoj'),
    ('Sacatepéquez','0306','Santiago Sacatepéquez'),
    ('Sacatepéquez','0307','San Bartolomé Milpas Altas'),
    ('Sacatepéquez','0308','San Lucas Sacatepéquez'),
    ('Sacatepéquez','0309','Santa Lucía Milpas Altas'),
    ('Sacatepéquez','0310','Magdalena Milpas Altas'),
    ('Sacatepéquez','0311','Santa María de Jesús'),
    ('Sacatepéquez','0312','Ciudad Vieja'),
    ('Sacatepéquez','0313','San Miguel Dueñas'),
    ('Sacatepéquez','0314','Alotenango'),
    ('Sacatepéquez','0315','San Antonio Aguas Calientes'),
    ('Sacatepéquez','0316','Santa Catarina Barahona'),
    ('Chimaltenango','0401','Chimaltenango'),
    ('Chimaltenango','0402','San José Poaquil'),
    ('Chimaltenango','0403','San Martín Jilotepeque'),
    ('Chimaltenango','0404','Comalapa'),
    ('Chimaltenango','0405','Santa Apolonia'),
    ('Chimaltenango','0406','Tecpán Guatemala'),
    ('Chimaltenango','0407','Patzún'),
    ('Chimaltenango','0408','Pochuta'),
    ('Chimaltenango','0409','Patzicía'),
    ('Chimaltenango','0410','Santa Cruz Balanyá'),
    ('Chimaltenango','0411','Acatenango'),
    ('Chimaltenango','0412','Yepocapa'),
    ('Chimaltenango','0413','San Andrés Itzapa'),
    ('Chimaltenango','0414','Parramos'),
    ('Chimaltenango','0415','Zaragoza'),
    ('Chimaltenango','0416','El Tejar'),
    ('Escuintla','0501','Escuintla'),
    ('Escuintla','0502','Santa Lucía Cotzumalguapa'),
    ('Escuintla','0503','La Democracia'),
    ('Escuintla','0504','Siquinalá'),
    ('Escuintla','0505','Masagua'),
    ('Escuintla','0506','Tiquisate'),
    ('Escuintla','0507','La Gomera'),
    ('Escuintla','0508','Guanagazapa'),
    ('Escuintla','0509','San José'),
    ('Escuintla','0510','Iztapa'),
    ('Escuintla','0511','Palín'),
    ('Escuintla','0512','San Vicente Pacaya'),
    ('Escuintla','0513','Nueva Concepción'),
    ('Santa Rosa','0601','Cuilapa'),
    ('Santa Rosa','0602','Barberena'),
    ('Santa Rosa','0603','Santa Rosa de Lima'),
    ('Santa Rosa','0604','Casillas'),
    ('Santa Rosa','0605','San Rafael las Flores'),
    ('Santa Rosa','0606','Oratorio'),
    ('Santa Rosa','0607','San Juan Tecuaco'),
    ('Santa Rosa','0608','Chiquimulilla'),
    ('Santa Rosa','0609','Taxisco'),
    ('Santa Rosa','0610','Santa María Ixhuatán'),
    ('Santa Rosa','0611','Guazacapán'),
    ('Santa Rosa','0612','Santa Cruz Naranjo'),
    ('Santa Rosa','0613','Pueblo Nuevo Viñas'),
    ('Santa Rosa','0614','Nueva Santa Rosa'),
    ('Sololá','0701','Sololá'),
    ('Sololá','0702','San José Chacayá'),
    ('Sololá','0703','Santa María Visitación'),
    ('Sololá','0704','Santa Lucía Utatlán'),
    ('Sololá','0705','Nahualá'),
    ('Sololá','0706','Santa Catarina Ixtahuacán'),
    ('Sololá','0707','Santa Clara la Laguna'),
    ('Sololá','0708','Concepción'),
    ('Sololá','0709','San Andrés Semetabaj'),
    ('Sololá','0710','Panajachel'),
    ('Sololá','0711','Santa Catarina Palopó'),
    ('Sololá','0712','San Antonio Palopó'),
    ('Sololá','0713','San Lucas Tolimán'),
    ('Sololá','0714','Santa Cruz la Laguna'),
    ('Sololá','0715','San Pablo la Laguna'),
    ('Sololá','0716','San Marcos la Laguna'),
    ('Sololá','0717','San Juan la Laguna'),
    ('Sololá','0718','San Pedro la Laguna'),
    ('Sololá','0719','Santiago Atitlán'),
    ('Totonicapán','0801','Totonicapán'),
    ('Totonicapán','0802','San Cristóbal Totonicapán'),
    ('Totonicapán','0803','San Francisco el Alto'),
    ('Totonicapán','0804','San Andrés Xecul'),
    ('Totonicapán','0805','Momostenango'),
    ('Totonicapán','0806','Santa María Chiquimula'),
    ('Totonicapán','0807','Santa Lucía la Reforma'),
    ('Totonicapán','0808','San Bartolo'),
    ('Quetzaltenango','0901','Quetzaltenango'),
    ('Quetzaltenango','0902','Salcajá'),
    ('Quetzaltenango','0903','Olintepeque'),
    ('Quetzaltenango','0904','San Carlos Sija'),
    ('Quetzaltenango','0905','Sibilia'),
    ('Quetzaltenango','0906','Cabricán'),
    ('Quetzaltenango','0907','Cajolá'),
    ('Quetzaltenango','0908','San Miguel Siguilá'),
    ('Quetzaltenango','0909','Ostuncalco'),
    ('Quetzaltenango','0910','San Mateo'),
    ('Quetzaltenango','0911','Concepción Chiquirichapa'),
    ('Quetzaltenango','0912','San Martín Sacatepéquez'),
    ('Quetzaltenango','0913','Almolonga'),
    ('Quetzaltenango','0914','Cantel'),
    ('Quetzaltenango','0915','Huitán'),
    ('Quetzaltenango','0916','Zunil'),
    ('Quetzaltenango','0917','Colomba'),
    ('Quetzaltenango','0918','San Francisco la Unión'),
    ('Quetzaltenango','0919','El Palmar'),
    ('Quetzaltenango','0920','Coatepeque'),
    ('Quetzaltenango','0921','Génova'),
    ('Quetzaltenango','0922','Flores Costa Cuca'),
    ('Quetzaltenango','0923','La Esperanza'),
    ('Quetzaltenango','0924','Palestina de los Altos'),
    ('Suchitepéquez','1001','Mazatenango'),
    ('Suchitepéquez','1002','Cuyotenango'),
    ('Suchitepéquez','1003','San Francisco Zapotitlán'),
    ('Suchitepéquez','1004','San Bernardino'),
    ('Suchitepéquez','1005','San José el Idolo'),
    ('Suchitepéquez','1006','Santo Domingo Suchitepéquez'),
    ('Suchitepéquez','1007','San Lorenzo'),
    ('Suchitepéquez','1008','Samayac'),
    ('Suchitepéquez','1009','San Pablo Jocopilas'),
    ('Suchitepéquez','1010','San Antonio Suchitepéquez'),
    ('Suchitepéquez','1011','San Miguel Panán'),
    ('Suchitepéquez','1012','San Gabriel'),
    ('Suchitepéquez','1013','Chicacao'),
    ('Suchitepéquez','1014','Patulul'),
    ('Suchitepéquez','1015','Santa Bárbara'),
    ('Suchitepéquez','1016','San Juan Bautista'),
    ('Suchitepéquez','1017','Santo Tomás la Unión'),
    ('Suchitepéquez','1018','Zunilito'),
    ('Suchitepéquez','1019','Pueblo Nuevo'),
    ('Suchitepéquez','1020','Río Bravo'),
    ('Suchitepéquez','1021','San José La Máquina'),
    ('Retalhuleu','1101','Retalhuleu'),
    ('Retalhuleu','1102','San Sebastián'),
    ('Retalhuleu','1103','Santa Cruz Muluá'),
    ('Retalhuleu','1104','San Martín Zapotitlán'),
    ('Retalhuleu','1105','San Felipe'),
    ('Retalhuleu','1106','San Andrés Villa Seca'),
    ('Retalhuleu','1107','Champerico'),
    ('Retalhuleu','1108','Nuevo San Carlos'),
    ('Retalhuleu','1109','El Asintal'),
    ('San Marcos','1201','San Marcos'),
    ('San Marcos','1202','San Pedro Sacatepéquez'),
    ('San Marcos','1203','San Antonio Sacatepéquez'),
    ('San Marcos','1204','Comitancillo'),
    ('San Marcos','1205','San Miguel Ixtahuacán'),
    ('San Marcos','1206','Concepción Tutuapa'),
    ('San Marcos','1207','Tacaná'),
    ('San Marcos','1208','Sibinal'),
    ('San Marcos','1209','Tajumulco'),
    ('San Marcos','1210','Tejutla'),
    ('San Marcos','1211','San Rafael Pié de la Cuesta'),
    ('San Marcos','1212','Nuevo Progreso'),
    ('San Marcos','1213','El Tumbador'),
    ('San Marcos','1214','El Rodeo'),
    ('San Marcos','1215','Malacatán'),
    ('San Marcos','1216','Catarina'),
    ('San Marcos','1217','Ayutla'),
    ('San Marcos','1218','Ocós'),
    ('San Marcos','1219','San Pablo'),
    ('San Marcos','1220','El Quetzal'),
    ('San Marcos','1221','La Reforma'),
    ('San Marcos','1222','Pajapita'),
    ('San Marcos','1223','Ixchiguán'),
    ('San Marcos','1224','San José Ojetenán'),
    ('San Marcos','1225','San Cristóbal Cucho'),
    ('San Marcos','1226','Sipacapa'),
    ('San Marcos','1227','Esquipulas Palo Gordo'),
    ('San Marcos','1228','Río Blanco'),
    ('San Marcos','1229','San Lorenzo'),
    ('San Marcos','1230','La Blanca'),
    ('Huehuetenango','1301','Huehuetenango'),
    ('Huehuetenango','1302','Chiantla'),
    ('Huehuetenango','1303','Malacatancito'),
    ('Huehuetenango','1304','Cuilco'),
    ('Huehuetenango','1305','Nentón'),
    ('Huehuetenango','1306','San Pedro Necta'),
    ('Huehuetenango','1307','Jacaltenango'),
    ('Huehuetenango','1308','Soloma'),
    ('Huehuetenango','1309','Ixtahuacán'),
    ('Huehuetenango','1310','Santa Bárbara'),
    ('Huehuetenango','1311','La Libertad'),
    ('Huehuetenango','1312','La Democracia'),
    ('Huehuetenango','1313','San Miguel Acatán'),
    ('Huehuetenango','1314','San Rafael la Independencia'),
    ('Huehuetenango','1315','Todos Santos Cuchumatán'),
    ('Huehuetenango','1316','San Juan Atitán'),
    ('Huehuetenango','1317','Santa Eulalia'),
    ('Huehuetenango','1318','San Mateo Ixtatán'),
    ('Huehuetenango','1319','Colotenango'),
    ('Huehuetenango','1320','San Sebastián Huehuetenango'),
    ('Huehuetenango','1321','Tectitán'),
    ('Huehuetenango','1322','Concepción Huista'),
    ('Huehuetenango','1323','San Juan Ixcoy'),
    ('Huehuetenango','1324','San Antonio Huista'),
    ('Huehuetenango','1325','San Sebastián Coatán'),
    ('Huehuetenango','1326','Barillas'),
    ('Huehuetenango','1327','Aguacatán'),
    ('Huehuetenango','1328','San Rafael Petzal'),
    ('Huehuetenango','1329','San Gaspar Ixchil'),
    ('Huehuetenango','1330','Santiago Chimaltenango'),
    ('Huehuetenango','1331','Santa Ana Huista'),
    ('Huehuetenango','1332','Unión Cantinil'),
    ('Quiché','1401','Santa Cruz del Quiché'),
    ('Quiché','1402','Chiché'),
    ('Quiché','1403','Chinique'),
    ('Quiché','1404','Zacualpa'),
    ('Quiché','1405','Chajul'),
    ('Quiché','1406','Chichicastenango'),
    ('Quiché','1407','Patzité'),
    ('Quiché','1408','San Antonio Ilotenango'),
    ('Quiché','1409','San Pedro Jocopilas'),
    ('Quiché','1410','Cunén'),
    ('Quiché','1411','San Juan Cotzal'),
    ('Quiché','1412','Joyabaj'),
    ('Quiché','1413','Nebaj'),
    ('Quiché','1414','San Andrés Sajcabajá'),
    ('Quiché','1415','Uspantán'),
    ('Quiché','1416','Sacapulas'),
    ('Quiché','1417','San Bartolomé Jocotenango'),
    ('Quiché','1418','Canillá'),
    ('Quiché','1419','Chicamán'),
    ('Quiché','1420','Ixcán'),
    ('Quiché','1421','Pachalum'),
    ('Baja Verapaz','1501','Salamá'),
    ('Baja Verapaz','1502','San Miguel Chicaj'),
    ('Baja Verapaz','1503','Rabinal'),
    ('Baja Verapaz','1504','Cubulco'),
    ('Baja Verapaz','1505','Granados'),
    ('Baja Verapaz','1506','El Chol'),
    ('Baja Verapaz','1507','San Jerónimo'),
    ('Baja Verapaz','1508','Purulhá'),
    ('Alta Verapaz','1601','Cobán'),
    ('Alta Verapaz','1602','Santa Cruz Verapaz'),
    ('Alta Verapaz','1603','San Cristóbal Verapaz'),
    ('Alta Verapaz','1604','Tactic'),
    ('Alta Verapaz','1605','Tamahú'),
    ('Alta Verapaz','1606','Tucurú'),
    ('Alta Verapaz','1607','Panzós'),
    ('Alta Verapaz','1608','Senahú'),
    ('Alta Verapaz','1609','San Pedro Carchá'),
    ('Alta Verapaz','1610','San Juan Chamelco'),
    ('Alta Verapaz','1611','Lanquín'),
    ('Alta Verapaz','1612','Cahabón'),
    ('Alta Verapaz','1613','Chisec'),
    ('Alta Verapaz','1614','Chahal'),
    ('Alta Verapaz','1615','Fray Bartolomé de las Casas'),
    ('Alta Verapaz','1616','Santa Catalina la Tinta'),
    ('Alta Verapaz','1617','Raxruhá'),
    ('Petén','1701','Flores'),
    ('Petén','1702','San José'),
    ('Petén','1703','San Benito'),
    ('Petén','1704','San Andrés'),
    ('Petén','1705','La Libertad'),
    ('Petén','1706','San Francisco'),
    ('Petén','1707','Santa Ana'),
    ('Petén','1708','Dolores'),
    ('Petén','1709','San Luis'),
    ('Petén','1710','Sayaxché'),
    ('Petén','1711','Melchor de Mencos'),
    ('Petén','1712','Poptún'),
    ('Petén','1713','Las Cruces'),
    ('Petén','1714','El Chal'),
    ('Izabal','1801','Puerto Barrios'),
    ('Izabal','1802','Livingston'),
    ('Izabal','1803','El Estor'),
    ('Izabal','1804','Morales'),
    ('Izabal','1805','Los Amates'),
    ('Zacapa','1901','Zacapa'),
    ('Zacapa','1902','Estanzuela'),
    ('Zacapa','1903','Río Hondo'),
    ('Zacapa','1904','Gualán'),
    ('Zacapa','1905','Teculután'),
    ('Zacapa','1906','Usumatlán'),
    ('Zacapa','1907','Cabañas'),
    ('Zacapa','1908','San Diego'),
    ('Zacapa','1909','La Unión'),
    ('Zacapa','1910','Huité'),
    ('Zacapa','1911','San Jorge'),
    ('Chiquimula','2001','Chiquimula'),
    ('Chiquimula','2002','San José La Arada'),
    ('Chiquimula','2003','San Juan Ermita'),
    ('Chiquimula','2004','Jocotán'),
    ('Chiquimula','2005','Camotán'),
    ('Chiquimula','2006','Olopa'),
    ('Chiquimula','2007','Esquipulas'),
    ('Chiquimula','2008','Concepción Las Minas'),
    ('Chiquimula','2009','Quetzaltepeque'),
    ('Chiquimula','2010','San Jacinto'),
    ('Chiquimula','2011','Ipala'),
    ('Jalapa','2101','Jalapa'),
    ('Jalapa','2102','San Pedro Pinula'),
    ('Jalapa','2103','San Luis Jilotepeque'),
    ('Jalapa','2104','San Manuel Chaparrón'),
    ('Jalapa','2105','San Carlos Alzatate'),
    ('Jalapa','2106','Monjas'),
    ('Jalapa','2107','Mataquescuintla'),
    ('Jutiapa','2201','Jutiapa'),
    ('Jutiapa','2202','El Progreso'),
    ('Jutiapa','2203','Santa Catarina Mita'),
    ('Jutiapa','2204','Agua Blanca'),
    ('Jutiapa','2205','Asunción Mita'),
    ('Jutiapa','2206','Yupiltepeque'),
    ('Jutiapa','2207','Atescatempa'),
    ('Jutiapa','2208','Jerez'),
    ('Jutiapa','2209','El Adelanto'),
    ('Jutiapa','2210','Zapotitlán'),
    ('Jutiapa','2211','Comapa'),
    ('Jutiapa','2212','Jalpatagua'),
    ('Jutiapa','2213','Conguaco'),
    ('Jutiapa','2214','Moyuta'),
    ('Jutiapa','2215','Pasaco'),
    ('Jutiapa','2216','San José Acatempa'),
    ('Jutiapa','2217','Quesada'),
]

def limpiar_strings(valor):
    return valor.encode('latin-1').decode('raw_unicode_escape').encode('latin-1').decode('utf-8')

def insert_municipios():
    arreglo = []
    deptos = Departamento.objects.all()
    for municipio in Municipios:
        depto = deptos.get(descripcion=limpiar_strings(municipio[0]))
        arreglo.append(
            Municipio(
                codigo=municipio[1], 
                descripcion=limpiar_strings(municipio[2]), 
                departamento=depto
            )
        )
    print(Municipio.objects.bulk_create(arreglo))

def insert_departamentos():
    arreglo = []
    for departamento in Departamentos:
        arreglo.append(
            Departamento(
                codigo=departamento[0], 
                descripcion=limpiar_strings(departamento[1])
            )
        )
    print(Departamento.objects.bulk_create(arreglo))
    insert_municipios()

insert_departamentos()
# > python manage.py shell < <nombre>.py